services:
  - type: web
    name: api-classificador-img
    runtime: python
    plan: free

    pythonVersion: 3.11.9

    buildCommand: pip install --no-cache-dir -r requirements.txt

    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 main:app